# Generated by Django 2.2.17 on 2021-02-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(null=True)),
                ('posting_date', models.DateField(null=True)),
                ('category', models.CharField(choices=[('HL', 'Head Line'), ('MP', 'Middle Page'), ('A', 'Advertization')], max_length=100, null=True, verbose_name='Category')),
                ('timeline', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(blank=True, to='articles.ArticleTag')),
            ],
        ),
    ]
